-- V1 baseline schema: full schema as of project inception
-- Matches the Hibernate 6 entity mappings with Spring's CamelCaseToUnderscoresNamingStrategy

CREATE TABLE about (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255),
    title       VARCHAR(255),
    description TEXT,
    about_text  TEXT
);

CREATE TABLE about_technologies (
    about_id  BIGINT NOT NULL,
    name      VARCHAR(255),
    image_url VARCHAR(255),
    CONSTRAINT fk_about_technologies_about FOREIGN KEY (about_id) REFERENCES about (id)
);

CREATE TABLE about_links (
    about_id BIGINT NOT NULL,
    label    VARCHAR(255),
    url      VARCHAR(255),
    CONSTRAINT fk_about_links_about FOREIGN KEY (about_id) REFERENCES about (id)
);

CREATE TABLE resume (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name VARCHAR(255),
    title     VARCHAR(255),
    email     VARCHAR(255),
    phone     VARCHAR(255),
    about     TEXT,
    version   BIGINT
);

CREATE TABLE resume_links (
    resume_id BIGINT NOT NULL,
    label     VARCHAR(255),
    url       VARCHAR(255),
    CONSTRAINT fk_resume_links_resume FOREIGN KEY (resume_id) REFERENCES resume (id)
);

CREATE TABLE experience (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name  VARCHAR(255),
    description   VARCHAR(255),
    start_date    DATE,
    end_date      DATE,
    display_order INTEGER,
    resume_id     BIGINT,
    CONSTRAINT fk_experience_resume FOREIGN KEY (resume_id) REFERENCES resume (id)
);

CREATE TABLE post_entity (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title            VARCHAR(255),
    content          TEXT,
    header_image_url VARCHAR(255),
    created_at       TIMESTAMP(6) NOT NULL
);
